#!/usr/bin/env python3
"""Produce hash-bound, file-by-file technical evidence for Debian distribution review.

This tool reports provenance signals; it does not determine legal ownership or grant
redistribution rights. Missing/ambiguous legal evidence remains HOLD.
"""
from __future__ import annotations

import argparse
import ast
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

SOURCE_GROUPS = (
    "bridge/*.py",
    "bridge/*.json",
    "bridge/deploy/*.service.in",
    "bridge/deploy/*.timer.in",
    "bridge/MTLS_READONLY_GATEWAY.md",
    "bridge/LIVE_TRANSPORT.md",
    "bridge/README.md",
    "scripts/provision-mtls-local.sh",
)
DOC_DEST = {
    "bridge/MTLS_READONLY_GATEWAY.md": "usr/share/louksna/MTLS_READONLY_GATEWAY.md",
    "bridge/LIVE_TRANSPORT.md": "usr/share/louksna/LIVE_TRANSPORT.md",
    "bridge/README.md": "usr/share/louksna/README.md",
}
PATTERNS = {
    "copyright_or_spdx": re.compile(r"copyright|SPDX-License-Identifier|SPDX-FileCopyrightText|licensed under|all rights reserved", re.I),
    "external_url": re.compile(r"https?://[^\s\"'<>]+", re.I),
    "third_party_signal": re.compile(r"third.party|vendored|vendorized|generated by|copied from|adapted from|upstream", re.I),
}
CREDENTIAL_NAME = re.compile(r"(TOKEN|SECRET|PASSWORD|API_KEY|PRIVATE_KEY)", re.I)


def run(args: list[str], *, cwd: Path, check: bool = True) -> str:
    result = subprocess.run(args, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if check and result.returncode:
        raise RuntimeError(f"command failed ({result.returncode}): {' '.join(args)}\n{result.stderr[-4000:]}")
    return result.stdout.strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tracked_sources(root: Path) -> list[Path]:
    tracked = set(run(["git", "ls-files", "--cached"], cwd=root).splitlines())
    found: set[str] = set()
    for pattern in SOURCE_GROUPS:
        for path in root.glob(pattern):
            rel = path.relative_to(root).as_posix()
            if rel in tracked and path.is_file():
                found.add(rel)
    return sorted(found)


def destinations(source: str) -> list[str]:
    if source.startswith("bridge/") and source.endswith((".py", ".json")):
        result = ["usr/lib/louksna/bridge/" + Path(source).name]
        if source == "bridge/CONTRACT.v0.json":
            result.append("usr/share/doc/louksna-linux-bridge/CONTRACT.v0.json")
        return result
    if source == "scripts/provision-mtls-local.sh":
        return ["usr/lib/louksna/bridge/provision-mtls-local.sh"]
    if source.startswith("bridge/deploy/"):
        result = ["usr/share/louksna/deploy/" + Path(source).name]
        if source == "bridge/deploy/louksna-mtls-readonly.service.in":
            result.append("lib/systemd/system/louksna-mtls-readonly.service")
        return result
    if source in DOC_DEST:
        return [DOC_DEST[source]]
    return []


def git_history(root: Path, rel: str) -> dict:
    output = run(
        ["git", "log", "--follow", "--format=%H%x09%aI%x09%an%x09%ae%x09%cN%x09%cE%x09%G?", "--", rel],
        cwd=root, check=False,
    )
    entries = [line.split("\t") for line in output.splitlines() if line.strip()]
    first = entries[-1] if entries else []
    return {
        "history_entries": len(entries),
        "latest_commit": entries[0][0] if entries else None,
        "first_recorded_introduction": {
            "commit": first[0], "author_date": first[1], "author_name": first[2],
            "author_email": first[3], "committer_name": first[4],
            "committer_email": first[5], "signature_status": first[6],
        } if len(first) >= 7 else None,
        "interpretation": "Git metadata is chronology/attribution evidence, not proof of legal authorship, assignment, or ownership.",
    }


def file_signals(path: Path, root: Path) -> dict:
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="replace")
    hits = {}
    for key, pattern in PATTERNS.items():
        values = []
        for line_no, line in enumerate(text.splitlines(), 1):
            if pattern.search(line):
                value = line.strip()
                if key == "external_url":
                    value = pattern.search(line).group(0).rstrip(".,);]")
                values.append({"line": line_no, "text": value[:300]})
        hits[key] = values[:100]
    imports = []
    if path.suffix == ".py":
        try:
            tree = ast.parse(text)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    imports.extend({"module": alias.name.split(".")[0], "line": node.lineno} for alias in node.names)
                elif isinstance(node, ast.ImportFrom) and node.module:
                    imports.append({"module": node.module.split(".")[0], "line": node.lineno})
        except SyntaxError as exc:
            imports.append({"module": "<SYNTAX_ERROR>", "line": exc.lineno, "detail": exc.msg})
    local_roots = {p.name for p in (root / "bridge").glob("*.py")}
    local_roots = {Path(name).stem for name in local_roots} | {"bridge"}
    stdlib = getattr(sys, "stdlib_module_names", set())
    for item in imports:
        name = item["module"]
        item["classification"] = "LOCAL_PROJECT" if name in local_roots else ("PYTHON_STDLIB" if name in stdlib else "REQUIRES_REVIEW")
    return {
        "sha256": hashlib.sha256(raw).hexdigest(),
        "size_bytes": len(raw),
        "signals": hits,
        "python_imports": imports,
        "license_signal_found": bool(hits["copyright_or_spdx"]),
        "interpretation": "A missing header signal is not proof that no license or third-party material applies.",
    }


def package_paths(package: Path, root: Path) -> set[str]:
    output = run(["dpkg-deb", "--contents", str(package.resolve())], cwd=root)
    paths = set()
    for line in output.splitlines():
        parts = line.split()
        if parts:
            name = parts[-1].lstrip("./")
            if name:
                paths.add(name)
    return paths


def parse_control(root: Path) -> dict:
    text = (root / "debian/control").read_text(encoding="utf-8")
    fields = {}
    for line in text.splitlines():
        if line and not line[0].isspace() and ": " in line:
            key, value = line.split(": ", 1)
            fields[key] = value
        elif line[:1].isspace() and fields:
            key = next(reversed(fields))
            fields[key] += " " + line.strip()
    return {
        "source": fields.get("Source"),
        "maintainer": fields.get("Maintainer"),
        "build_depends": fields.get("Build-Depends", ""),
        "runtime_depends": fields.get("Depends", ""),
        "recommends": fields.get("Recommends", ""),
        "placeholder_contact": ".invalid" in fields.get("Maintainer", ""),
        "interpretation": "Declared Debian dependencies are not the same as vendored/bundled components; this field alone is not a complete dependency audit.",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package", required=True, type=Path, help="built .deb to compare against source rules")
    parser.add_argument("--output", default=Path("distribution-audit.json"), type=Path)
    args = parser.parse_args()
    root = Path(run(["git", "rev-parse", "--show-toplevel"], cwd=Path.cwd())).resolve()
    package = args.package.resolve()
    if not package.is_file():
        parser.error(f"package does not exist: {package}")
    sources = tracked_sources(root)
    actual_package_paths = package_paths(package, root)
    source_rows = []
    expected_installed = set()
    for rel in sources:
        path = root / rel
        mapped = destinations(rel)
        expected_installed.update(mapped)
        source_rows.append({
            "source_path": rel,
            "installed_destinations": mapped,
            **file_signals(path, root),
            "git_history": git_history(root, rel),
        })
    missing_from_package = sorted(expected_installed - actual_package_paths)
    unresolved_imports = sorted({
        item["module"]
        for row in source_rows for item in row["python_imports"]
        if item["classification"] == "REQUIRES_REVIEW"
    })
    package_digest = sha256(package)
    clearance_path = root / "docs/DISTRIBUTION_CLEARANCE.json"
    copyright_path = root / "debian/copyright"
    report = {
        "schema": "LOUKSNA_DISTRIBUTION_FORENSIC_AUDIT/1.0",
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository": run(["git", "config", "--get", "remote.origin.url"], cwd=root, check=False),
        "branch": run(["git", "branch", "--show-current"], cwd=root, check=False),
        "commit_sha": run(["git", "rev-parse", "HEAD"], cwd=root),
        "package": {
            "path": str(package),
            "filename": package.name,
            "size_bytes": package.stat().st_size,
            "sha256": package_digest,
            "dpkg_deb_version": run(["dpkg-deb", "--version"], cwd=root).splitlines()[0],
        },
        "source_coverage": {
            "source_file_count": len(source_rows),
            "expected_source_file_count_from_prior_review": 30,
            "count_matches_prior_review": len(source_rows) == 30,
            "files": source_rows,
            "expected_installed_paths_missing_from_package": missing_from_package,
            "source_mapping_complete": len(source_rows) == 30 and not missing_from_package,
        },
        "dependencies": {
            "debian_control": parse_control(root),
            "python_import_roots_requiring_review": unresolved_imports,
            "remote_provider_signals": [
                {"source_path": row["source_path"], "urls": row["signals"]["external_url"]}
                for row in source_rows if row["signals"]["external_url"]
            ],
            "provider_weights_bundled": "NOT_DETERMINED_BY_SOURCE_SCAN",
            "transitive_dependency_closure": "NOT_PROVEN_BY_STATIC_IMPORT_SCAN",
        },
        "distribution_rights": {
            "debian_copyright_exists": copyright_path.is_file(),
            "distribution_clearance_record_exists": clearance_path.is_file(),
            "status": "HOLD" if not copyright_path.is_file() or not clearance_path.is_file() else "REQUIRES_INDEPENDENT_VALIDATION",
            "rights_holder": "UNVERIFIED",
            "redistribution_authorization": "UNVERIFIED",
            "third_party_clearance": "INCOMPLETE",
            "do_not_infer_license_from_git_metadata": True,
        },
        "maintainer_contact": {
            **parse_control(root),
            "status": "UNVERIFIED" if parse_control(root)["placeholder_contact"] else "REQUIRES_DIRECT_VERIFICATION",
        },
        "build_validation": {
            "source_package_file_list": sorted(actual_package_paths),
            "lintian_must_be_run_separately": True,
            "g23": "NOT_EXECUTED",
            "g24": "NOT_EXECUTED",
            "host_mtls_handshake": "NOT_TESTED_BY_THIS_STATIC_AUDIT",
            "rollback_and_postboot": "NOT_TESTED_ON_HOST",
        },
        "result": "HOLD" if (
            len(source_rows) != 30 or missing_from_package or not copyright_path.is_file()
            or not clearance_path.is_file() or unresolved_imports
        ) else "REQUIRES_INDEPENDENT_VALIDATION",
        "limitations": [
            "This report is technical provenance evidence, not legal advice or a rights grant.",
            "Git author/committer metadata and unsigned/signed status do not prove legal ownership.",
            "Static source scans cannot establish absence of copied/derived material.",
            "No network lookup, license compatibility ruling, model-weight audit, host mTLS handshake, G23 or G24 certification is performed by this script.",
            "A HOLD report is an expected valid diagnostic outcome while legal evidence is absent.",
        ],
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "schema": report["schema"], "commit_sha": report["commit_sha"],
        "package_sha256": package_digest, "source_file_count": len(source_rows),
        "missing_from_package": missing_from_package,
        "unresolved_imports": unresolved_imports,
        "debian_copyright_exists": copyright_path.is_file(),
        "clearance_record_exists": clearance_path.is_file(),
        "result": report["result"], "output": str(args.output),
    }, indent=2))
    return 0 if report["source_coverage"]["source_mapping_complete"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
