#!/bin/sh
# Explicitly provision local-only TLS identities. Never starts/enables systemd.
set -eu
umask 077

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: execute with sudo; this provisions root-controlled TLS policy." >&2
  exit 2
fi
if [ -z "${SUDO_UID:-}" ] || [ "$SUDO_UID" -eq 0 ]; then
  echo "ERROR: invoke with sudo from the intended owner account (not a root login)." >&2
  exit 2
fi

OWNER_UID="$SUDO_UID"
OWNER_ENTRY="$(getent passwd "$OWNER_UID")"
OWNER_HOME="$(printf '%s' "$OWNER_ENTRY" | cut -d: -f6)"
OWNER_GID="$(printf '%s' "$OWNER_ENTRY" | cut -d: -f4)"
[ -n "$OWNER_HOME" ] && [ -d "$OWNER_HOME" ] || { echo "ERROR: owner home not found" >&2; exit 2; }

BASE=/etc/louksna/remote-bridge
TLS="$BASE/tls"
CLIENT="$OWNER_HOME/.config/louksna/mtls"
CONFIG="$BASE/mtls.json"

# Fail closed: validate trusted parents and never overwrite prior trust material.
for d in /etc/louksna "$BASE"; do
  if [ -L "$d" ]; then
    echo "ERROR: symlinked trust-policy directory: $d" >&2
    exit 3
  fi
  if [ -e "$d" ]; then
    [ -d "$d" ] && [ "$(stat -c %u "$d")" = 0 ] &&
      [ $(( 0$(stat -c %a "$d") & 022 )) -eq 0 ] || {
        echo "ERROR: unsafe trust-policy directory ownership/mode: $d" >&2
        exit 3
      }
  fi
done
for p in "$CONFIG" "$TLS" "$CLIENT"; do
  if [ -e "$p" ] || [ -L "$p" ]; then
    echo "ERROR: existing trust material found at $p; refusing overwrite." >&2
    exit 3
  fi
done

# Existing owner config ancestors must be real directories owned by the owner.
for d in "$OWNER_HOME/.config" "$OWNER_HOME/.config/louksna"; do
  if [ -e "$d" ] || [ -L "$d" ]; then
    [ -d "$d" ] && [ ! -L "$d" ] && [ "$(stat -c %u "$d")" = "$OWNER_UID" ] || {
      echo "ERROR: owner config directory has unexpected type/ownership: $d" >&2
      exit 3
    }
  fi
done

VALIDATED=0
BASE_PARENT_CREATED=0
BASE_CREATED=0
TLS_CREATED=0
CLIENT_CREATED=0
cleanup() {
  # Delete only named artifacts generated by this invocation; never recursively
  # delete a directory that may have acquired unrelated content.
  if [ "$VALIDATED" -ne 1 ]; then
    rm -f "$CONFIG" \
      "$TLS/ca.key" "$TLS/ca.pem" "$TLS/ca.srl" \
      "$TLS/server.key" "$TLS/server.pem" "$TLS/server.csr" "$TLS/server.ext" \
      "$TLS/client.csr" "$TLS/client.ext" \
      "$CLIENT/client.key" "$CLIENT/client.pem" "$CLIENT/ca.pem"
    [ "$TLS_CREATED" -eq 1 ] && rmdir "$TLS" 2>/dev/null || true
    [ "$CLIENT_CREATED" -eq 1 ] && rmdir "$CLIENT" 2>/dev/null || true
    [ "$BASE_CREATED" -eq 1 ] && rmdir "$BASE" 2>/dev/null || true
    [ "$BASE_PARENT_CREATED" -eq 1 ] && rmdir /etc/louksna 2>/dev/null || true
  fi
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

if [ ! -e /etc/louksna ]; then
  install -d -o root -g root -m 0755 /etc/louksna
  BASE_PARENT_CREATED=1
fi
if [ ! -e "$BASE" ]; then
  install -d -o root -g root -m 0755 "$BASE"
  BASE_CREATED=1
fi
install -d -o root -g root -m 0700 "$TLS"
TLS_CREATED=1
for d in "$OWNER_HOME/.config" "$OWNER_HOME/.config/louksna"; do
  if [ ! -e "$d" ]; then
    install -d -o "$OWNER_UID" -g "$OWNER_GID" -m 0700 "$d"
  fi
done
# Keep the client directory root-private while root writes into it. This blocks
# the invoking user from racing generated filenames with symlinks.
install -d -o root -g root -m 0700 "$CLIENT"
CLIENT_CREATED=1

openssl req -x509 -newkey rsa:3072 -nodes -sha256 \
  -keyout "$TLS/ca.key" -out "$TLS/ca.pem" -days 365 \
  -subj "/CN=LOUKSNA Local mTLS CA" \
  -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
  -addext "keyUsage=critical,keyCertSign,cRLSign"
chmod 0600 "$TLS/ca.key"
chmod 0644 "$TLS/ca.pem"

openssl req -new -newkey rsa:3072 -nodes -sha256 \
  -keyout "$TLS/server.key" -out "$TLS/server.csr" \
  -subj "/CN=localhost"
chmod 0600 "$TLS/server.key"
cat > "$TLS/server.ext" <<'EOF'
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
subjectAltName=DNS:localhost,IP:127.0.0.1
EOF
openssl x509 -req -sha256 -in "$TLS/server.csr" \
  -CA "$TLS/ca.pem" -CAkey "$TLS/ca.key" -CAcreateserial \
  -out "$TLS/server.pem" -days 180 -extfile "$TLS/server.ext"
chmod 0644 "$TLS/server.pem"

openssl req -new -newkey rsa:3072 -nodes -sha256 \
  -keyout "$CLIENT/client.key" -out "$TLS/client.csr" \
  -subj "/CN=LOUKSNA Local Owner Client"
chmod 0600 "$CLIENT/client.key"
cat > "$TLS/client.ext" <<'EOF'
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=clientAuth
EOF
openssl x509 -req -sha256 -in "$TLS/client.csr" \
  -CA "$TLS/ca.pem" -CAkey "$TLS/ca.key" -CAcreateserial \
  -out "$CLIENT/client.pem" -days 180 -extfile "$TLS/client.ext"
chmod 0644 "$CLIENT/client.pem"
cp "$TLS/ca.pem" "$CLIENT/ca.pem"
chown "$OWNER_UID:$OWNER_GID" "$CLIENT/client.key" "$CLIENT/client.pem" "$CLIENT/ca.pem"
chmod 0600 "$CLIENT/client.key"
chmod 0644 "$CLIENT/client.pem" "$CLIENT/ca.pem"

CLIENT_PIN="$(openssl x509 -in "$CLIENT/client.pem" -outform DER | sha256sum | cut -d' ' -f1)"
SERVER_PIN="$(sha256sum "$TLS/server.pem" | cut -d' ' -f1)"
CA_PIN="$(sha256sum "$TLS/ca.pem" | cut -d' ' -f1)"
python3 - "$CONFIG" "$TLS/server.pem" "$TLS/server.key" "$TLS/ca.pem" "$CLIENT_PIN" "$SERVER_PIN" "$CA_PIN" <<'PY'
import json, os, sys, tempfile
config, server_cert, server_key, ca, client_pin, server_pin, ca_pin = sys.argv[1:]
data = {
    "schema": "LRB_MTLS_READONLY_GATEWAY/0.3",
    "server_cert": server_cert,
    "server_key": server_key,
    "client_ca": ca,
    "client_cert_sha256": client_pin,
    "server_cert_sha256": server_pin,
    "client_ca_sha256": ca_pin,
}
directory = os.path.dirname(config)
fd, tmp = tempfile.mkstemp(prefix=".mtls.json.", dir=directory, text=True)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, sort_keys=True, indent=2)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    os.chmod(tmp, 0o600)
    os.chown(tmp, 0, 0)
    os.replace(tmp, config)
except BaseException:
    try: os.unlink(tmp)
    except FileNotFoundError: pass
    raise
PY
chmod 0600 "$CONFIG"
chown root:root "$CONFIG"

# Validate against the installed gateway's real fail-closed checks before success.
PYTHONPATH=/usr/lib/louksna/bridge python3 - "$CONFIG" <<'PY'
import sys
import mtls_gateway
cfg = mtls_gateway.read_config(sys.argv[1], enforce_root=True)
print("CONFIG_VALIDATED schema=" + cfg["schema"])
PY

# Remove signing key and transient CSRs/extensions; retain CA certificate for server trust.
# Keep VALIDATED=0 until every publication/permission operation has succeeded, so
# any failure still takes the bounded rollback path.
rm -f "$TLS/ca.key" "$TLS/server.csr" "$TLS/server.ext" "$TLS/client.csr" "$TLS/client.ext" "$TLS/ca.srl"
# Publish the client identity only after all runtime-policy checks passed.
chown "$OWNER_UID:$OWNER_GID" "$CLIENT"
chmod 0700 "$CLIENT"
VALIDATED=1
trap - EXIT HUP INT TERM
echo "PROVISIONED: $CONFIG"
echo "CLIENT_IDENTITY: $CLIENT"
echo "SERVICE_STATE: left disabled and stopped; activation is a separate reviewed step."
